settings:
  index:
    # single node, no sharding
    number_of_shards: 1
    number_of_replicas: 0
mappings:
  articles:
    dynamic: false # disable dynamic mapping
    properties:
      title: &fr_text
        type: text
        analyzer: french
      linkedCategories: *fr_text
      linkedBrands: *fr_text
      content: *fr_text